---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tunnel.my.domain
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.my.domain
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - tunnel.my.domain
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tunnel.my.domain
  resources:
  - tunnelagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.my.domain
  resources:
  - tunnelagents/finalizers
  verbs:
  - update
- apiGroups:
  - tunnel.my.domain
  resources:
  - tunnelagents/status
  verbs:
  - get
  - patch
  - update
